//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourSquareVenueRecommendationsMetaData
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string DisplayString { get; set; }
        public string HeaderLocation { get; set; }
        public string HeaderLocationFull { get; set; }
        public string HeaderLocationGranularity { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string VenueId { get; set; }
        public string VenueName { get; set; }
        public string VenuePostalCode { get; set; }
        public string VenueCC { get; set; }
        public string VenueCity { get; set; }
        public string VenueState { get; set; }
        public string VenueCountry { get; set; }
        public string VenueFormattedAddress { get; set; }
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryPluralName { get; set; }
        public string CategoryShortName { get; set; }
        public string CategoryPrefix { get; set; }
        public string CategorySuffix { get; set; }
        public string UserSearchString { get; set; }
    }
}
