//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourSquarePhotoMetaData
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string PhotoId { get; set; }
        public string PhotoPrefix { get; set; }
        public string PhotoSuffix { get; set; }
        public string PhotoWidth { get; set; }
        public string PhotoHeight { get; set; }
        public string PhotoOwner { get; set; }
        public string PhotoVisibility { get; set; }
        public string VenueId { get; set; }
    }
}
