//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FourSquareVenueMetaData
    {
        public System.Guid Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string VenueId { get; set; }
        public string VenueName { get; set; }
        public string VenueAddress { get; set; }
        public string VenueCrossStreet { get; set; }
        public string VenueLatitude { get; set; }
        public string VenueLongitude { get; set; }
        public string VenuePostalCode { get; set; }
        public string VenueCC { get; set; }
        public string VenueCity { get; set; }
        public string VenueState { get; set; }
        public string VenueCountry { get; set; }
        public string VenueFormattedAddress { get; set; }
        public string VenueCategoryName { get; set; }
        public string VenueCategoryNamePlural { get; set; }
        public string VenueCategoryNameShort { get; set; }
        public string VenueCategoryPrefix { get; set; }
        public string VenueCategorySuffix { get; set; }
        public string SearchNameEnteredByUser { get; set; }
    }
}
